### ISSUE TITLE
Menu does not appear right

### ISSUE THREAD

**Issue by minidoc** [praveenpuglia/exercism.io#8]
The menu should fit properly.

![screen shot 2015-05-22 at 15 42 05](https://cloud.githubusercontent.com/assets/1484393/7768553/f6ef18b2-0099-11e5-9e6a-96413dd33b46.png)

**Comment by praveenpuglia** [comment]
Has been fixed with this commit - cf4e72173ec228e72d163324a156b1b4d14b20a5. Shall be available in the next build/deployment.

**Comment by minidoc** [comment]
May need more attention.

![screen shot 2015-05-22 at 16 02 27](https://cloud.githubusercontent.com/assets/1484393/7768776/15b61474-009c-11e5-9529-4d3126adb1e3.png)

**Comment by praveenpuglia** [comment]
We will be removing these menus entirely in future since those topics aren't something that should be available all the time on primary navigation. 

Also, I think it's overflowing in smaller screens. For now, adjusting the font sizes and padding should get the job done.

P.S - I didn't see the arrow-misalignment. Will fix it in next ui-fix commit. I'll keep the bug open until then.

**Comment by praveenpuglia** [comment]
This has been fixed in the latest commit. should be available in the next build.
